Web Framework/WebFramework/Controllers/GDriveController.cs
namespace WebFramework.Controllers
{
    using log4net;
    using Microsoft.AspNet.Identity;
    using Microsoft.Owin.Security;
    using Ninject;
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Security.Claims;
    using System.Web;
    using System.Web.Mvc;
    using WebFramework.App_Start;
    using WebFramework.Helpers;
    using WebFramework.Persistence.GDrive;

    [SecurityCode]
    public class GDriveController : BaseController
    {
        private readonly ILog _log;

        private readonly IGDriveDbContext _db;

        public GDriveController([Named(WebFramework.Helpers.Constants.ServerLoggerName)] ILog log, IGDriveDbContext db)
            : base(log)
        {
            _log = log;
            _db = db;
        }

        public ActionResult Index()
        {
            ViewBag.MaxNoOfFiles = ConfigManager.Get<string>("MaxNoOfFiles");
            ViewBag.MaxFileSize = ConfigManager.Get<decimal>("MaxFileSizeInMB");
            ViewBag.DriveFileFormats = ConfigManager.Get<string>("DriveFileFormats");

            return View();
        }

        [HttpPost]
        public ActionResult Index(System.Web.HttpPostedFileBase file)
        {
            var maxNoOfFiles = ConfigManager.Get<int>("MaxNoOfFiles");
            var maxFileSize = ConfigManager.Get<decimal>("MaxFileSizeInMB");
            var driveFileFormats = ConfigManager.Get<string>("DriveFileFormats");
            ViewBag.MaxNoOfFiles = maxNoOfFiles;
            ViewBag.MaxFileSize = maxFileSize;
            ViewBag.DriveFileFormats = driveFileFormats;

            var msg = string.Empty;
            if (file != null && file.ContentLength > 0)
            {
                try
                {
                    var formats = driveFileFormats.Split(new[] { "," }, StringSplitOptions.RemoveEmptyEntries).ToList();
                    var ext = file.FileName.Substring(file.FileName.LastIndexOf('.') + 1);

                    var identity = (ClaimsIdentity)User.Identity;
                    var claimsUserData = identity.Claims.FirstOrDefault(a => a.Type == "http://schemas.microsoft.com/ws/2008/06/identity/claims/userdata");
                    var superUser = false;
                    if (claimsUserData != null && claimsUserData.Value == ConfigManager.Get<string>("SecretSecurityCode"))
                    {
                        superUser = true;
                    }

                    var fileSize = ((decimal)file.ContentLength) / 1024.0m / 1024.0m; // in MB.
                    if (!superUser && fileSize > maxFileSize)
                    {
                        msg = "Selected file (" + fileSize.ToString("0.00") + "MB) is exceeding the limit.";
                    }
                    else if (!superUser && !formats.Any(a => a.Trim().Equals(ext, StringComparison.CurrentCultureIgnoreCase)))
                    {
                        msg = ext.ToUpper() + " file format is not accepted.";
                    }
                    else if (!superUser && GetNoOfFiles() > maxNoOfFiles)
                    {
                        msg = "You have reached your quota of files.";
                    }
                    else if (_db.Files.FirstOrDefault(f => f.FileName == file.FileName) != null)
                    {
                        msg = "File with same name already exists.";
                    }
                    else if (claimsUserData == null)
                    {
                        msg = "Unable to read your security code. Logout and log back in please.";
                    }
                    else
                    {
                        byte[] fileData = null;
                        using (var binaryReader = new BinaryReader(Request.Files[0].InputStream))
                        {
                            fileData = binaryReader.ReadBytes(Request.Files[0].ContentLength);
                        }
                        if (fileData == null || fileData.Length == 0)
                        {
                            return RedirectToAction("Index");
                        }

                        _db.Files.Add(new Models.GDrive.FileContent
                                                {
                                                    SecurityCode = claimsUserData.Value,
                                                    FileName = file.FileName,
                                                    UploadedOn = DateTime.Now,
                                                    Content = fileData
                                                });
                        _db.SaveChanges();

                        IncrementNoOfFiles();

                        Session["USER_MESSAGE"] = "Your file has been successfully uploaded.";
                        Session["USER_MESSAGE_SEVERITY"] = "Success";
                        Session["USER_MESSAGE_TITLE"] = "File Uploaded";

                        return RedirectToAction("Index");
                    }
                }
                catch (Exception ex)
                {
                    _log.Error("GDrive Upload", ex);
                    msg = "Sorry, an error occured while uploading your file. Please try again.";
                }
            }
            else
            {
                msg = "You have not specified a file.";
            }

            Session["USER_MESSAGE"] = msg;
            Session["USER_MESSAGE_SEVERITY"] = "Error";

            return RedirectToAction("Index");
        }

        public ActionResult Download(string file)
        {
            var fileContent = _db.Files.FirstOrDefault(f => f.FileName == file);
            if (fileContent == null)
            {
                Session["USER_MESSAGE"] = "File not found.";
                Session["USER_MESSAGE_SEVERITY"] = "Error";
                Session["USER_MESSAGE_TITLE"] = "File not found";

                return RedirectToAction("Index");
            }

            return File(fileContent.Content, GetContentType(fileContent.FileName));
        }

        public ActionResult Delete(string file)
        {
            if (!string.IsNullOrWhiteSpace(file))
            {
                var fileContent = _db.Files.FirstOrDefault(f => f.FileName == file);
                if (fileContent == null)
                {
                    Session["USER_MESSAGE"] = "File not found.";
                    Session["USER_MESSAGE_SEVERITY"] = "Error";
                    Session["USER_MESSAGE_TITLE"] = "File not found";

                    return RedirectToAction("Index");
                }

                _db.Files.Remove(fileContent);
                _db.SaveChanges();

                DecrementNoOfFiles();

                Session["USER_MESSAGE"] = "The file has been successfully deleted.";
                Session["USER_MESSAGE_SEVERITY"] = "Success";
                Session["USER_MESSAGE_TITLE"] = "File Deleted";

                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
        }

        public JsonResult GetFiles(string folder)
        {
            var identity = (ClaimsIdentity)User.Identity;
            var claimsUserData = identity.Claims.FirstOrDefault(a => a.Type == "http://schemas.microsoft.com/ws/2008/06/identity/claims/userdata");
            var t = _db.Files.Where(w => w.SecurityCode == claimsUserData.Value).Select(s => s.FileName).ToList();
            return new JsonResult { Data = t, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        private string GetContentType(string fileName)
        {
            var ext = fileName.Substring(fileName.LastIndexOf('.') + 1).ToUpper();
            switch (ext)
            {
                case "JPG":
                case "JPEG":
                    return "image/jpeg";

                case "PNG":
                    return "image/png";

                case "ZIP":
                    return "application/zip";

                default:
                    return string.Empty;
            }
        }

        private int GetNoOfFiles()
        {
            var cookie = Request.Cookies["NO_OF_FILES"];
            if (cookie != null)
            {
                var noOfFiles = 0;
                var value = cookie.Value ?? string.Empty;
                if (int.TryParse(value, out noOfFiles))
                {
                    return noOfFiles;
                }
            }

            return 0;
        }

        private void IncrementNoOfFiles()
        {
            var noOfFiles = GetNoOfFiles();
            var nextFileAt = DateTime.Now.Add(TimeSpan.FromMinutes(300));

            var cookie = new HttpCookie("NO_OF_FILES", (++noOfFiles).ToString());
            cookie.Expires = nextFileAt;
            Response.Cookies.Add(cookie);

            var expiry = new HttpCookie("NEXT_FILE_AT", nextFileAt.ToString());
            expiry.Expires = nextFileAt;
            Response.Cookies.Add(expiry);
        }

        private void DecrementNoOfFiles()
        {
            var noOfFiles = GetNoOfFiles();
            var nextFileAt = DateTime.Now.Add(TimeSpan.FromMinutes(300));

            var cookie = new HttpCookie("NO_OF_FILES", (--noOfFiles).ToString());
            cookie.Expires = nextFileAt;
            Response.Cookies.Add(cookie);

            var expiry = new HttpCookie("NEXT_FILE_AT", nextFileAt.ToString());
            expiry.Expires = nextFileAt;
            Response.Cookies.Add(expiry);
        }
    }
}

Web Framework/WebFramework/Controllers/SecurityController.cs
using log4net;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;
using Ninject;
using System;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using WebFramework.App_Start;
using WebFramework.Helpers;
namespace WebFramework.Controllers
{
    public class SecurityController : BaseController
    {
        private readonly ILog _log;

        public SecurityController([Named(WebFramework.Helpers.Constants.ServerLoggerName)] ILog log)
            : base(log)
        {
            _log = log;
        }

        [AllowAnonymous]
        public ActionResult Login(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            ViewBag.Code = ConfigManager.Get<string>("SecurityCode");

            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult Login(string code, string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            ViewBag.Code = ConfigManager.Get<string>("SecurityCode");

            var noOfTries = GetNoOfTries();
            if (noOfTries >= 5)
            {
                DateTime? nextCommentAt = GetNextTryAt();
                var laterOn = nextCommentAt.HasValue ? " after " + nextCommentAt.Value.ToString() : string.Empty;
                ModelState.AddModelError("", "Too many tries. Take a break and comeback" + laterOn + ".");
                return View();
            }

            if (ModelState.IsValid && 
               (ConfigManager.Get<string>("SecurityCode") == code || ConfigManager.Get<string>("SecretSecurityCode") == code))
            {
                var ident = new ClaimsIdentity(
                  new[] { 
                          // adding following 2 claim just for supporting default antiforgery provider
                          new Claim(ClaimTypes.NameIdentifier, "ValidatedUser"),
                          new Claim("http://schemas.microsoft.com/accesscontrolservice/2010/07/claims/identityprovider", 
                                    "ASP.NET Identity", 
                                    "http://www.w3.org/2001/XMLSchema#string"),

                          new Claim(ClaimTypes.Name, "ValidatedUser"),

                          new Claim(ClaimTypes.UserData, code),

                          // optionally you could add roles if any
                          new Claim(ClaimTypes.Role, "RoleName"),
                          new Claim(ClaimTypes.Role, "AnotherRole"),

                      },
                  DefaultAuthenticationTypes.ApplicationCookie);

                HttpContext.GetOwinContext().Authentication.SignIn(
                    new AuthenticationProperties 
                            {
                                IsPersistent = false, 
                                IssuedUtc = DateTime.UtcNow,
                                ExpiresUtc = DateTime.UtcNow.AddMinutes(5) 
                            }, 
                            ident);

                return RedirectToLocal(returnUrl);
            }
            else
            {
                IncrementNoOfTries();

                ModelState.AddModelError("", "Security failed.");
            }

            return View();
        }

        [SecurityCode]
        public ActionResult Logout(string returnUrl)
        {
            HttpContext.GetOwinContext().Authentication.SignOut(DefaultAuthenticationTypes.ApplicationCookie);

            return RedirectToLocal(returnUrl);
        }

        private ActionResult RedirectToLocal(string returnUrl)
        {
            if (!string.IsNullOrWhiteSpace(returnUrl) && Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }

            return RedirectToAction("Index", "Home");
        }

        private int GetNoOfTries()
        {
            var cookie = Request.Cookies["NO_OF_TRIES"];
            if (cookie != null)
            {
                var noOfTries = 0;
                var value = cookie.Value ?? string.Empty;
                if (int.TryParse(value, out noOfTries))
                {
                    return noOfTries;
                }
            }

            return 0;
        }

        private DateTime? GetNextTryAt()
        {
            var cookie = Request.Cookies["NEXT_TRY_AT"];
            if (cookie != null)
            {
                DateTime nextTryAt;
                var value = cookie.Value ?? string.Empty;
                if (DateTime.TryParse(value, out nextTryAt))
                {
                    return nextTryAt;
                }
            }

            return null;
        }

        private void IncrementNoOfTries()
        {
            var noOfTries = GetNoOfTries();
            var nextTryAt = DateTime.Now.Add(TimeSpan.FromMinutes(30));

            var cookie = new HttpCookie("NO_OF_TRIES", (++noOfTries).ToString());
            cookie.Expires = nextTryAt;
            Response.Cookies.Add(cookie);

            var expiry = new HttpCookie("NEXT_TRY_AT", nextTryAt.ToString());
            expiry.Expires = nextTryAt;
            Response.Cookies.Add(expiry);
        }
    }
}

Web Framework/WebFramework/Views/GDrive/Index.cshtml
@{
    ViewBag.Title = "Drive";
}

@section breadcrumbs {
    <ol class="breadcrumb">
        <li><a href="@Url.Action("Index", "Home")"><i class="fa fa-home fa-1_3x"></i></a></li>
        <li class="active">
            <a href="@Url.Action("Index", "GDrive")">GDrive</a>
            &nbsp;<span style="font-size: 0.8em">(<a href="@Url.Action("Logout", "Security", new { returnUrl = "/GDrive" })">Logout</a>)</span>
        </li>
    </ol>
}

<div style="padding-right: 35px">
    <fieldset class="col-lg-5 col-md-6 col-sm-12 col-xs-12" style="margin: 25px 0">
        <legend>Add Files To Drive</legend>
        @using (Html.BeginForm("Index", "GDrive", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken();
            <input type="file" name="file" id="file" style="display: inline" />
            <button class="btn btn-custom-success btn-sm" type="submit">Upload File</button>
            <br /><br />
            <div>Limitations: @ViewBag.MaxNoOfFiles file(s); @ViewBag.MaxFileSize MB each; @ViewBag.DriveFileFormats formats;</div>
        }

    </fieldset>
</div>

<div class="clearfix"></div>

<div class="list-group col-lg-5 col-md-6 col-sm-12 col-xs-12">

    <div class="list-group-item" style="background-color: #eee;">
        Uploaded Files &nbsp; <a href="#" onclick="LoadFiles(''); return false;"><i class="fa fa-home fa-0_7x"></i></a>
        <span id="navigation"></span>
    </div>

    <div id="list-of-files"></div>
</div>

@section pageStyle {
    @Styles.Render("~/bundles/form-data-styles")
}

@section pageScript {
    @Scripts.Render("~/bundles/form-data-validation")

    <script type="text/javascript">
        $(function () {
            LoadFiles('');
        });

        function LoadFiles(folder) {
            Invoke('/GDrive/GetFiles?folder=' + folder, '', 'GET', true, OnGetFiles);
        }

        function OnGetFiles(data) {
            var html = '';
            for (var i = 0; i < data.length; i++)
            {
                var location = data[i];//.substring(data[i].indexOf("DriveContents") + 14).replace(/\\/g, "/");

                var file = data[i].substring(data[i].lastIndexOf('\\') + 1);
                var isDir = true;
                var displayContents = '';
                var actionContents = '';
                if (file.toLowerCase().endsWith('.zip') || file.toLowerCase().endsWith('.jpg') || file.toLowerCase().endsWith('.jpeg') || file.toLowerCase().endsWith('.png')) {
                    isDir = false;
                    displayContents = file;
                    actionContents += '<div style="width: 25%; display: inline-block; text-align: right">';
                    actionContents += '<a href="/GDrive/Download?file=' + location + '" target="_blank"><i class="fa fa-download fa-1_3x"></i></a>';
                    actionContents += '&nbsp; &nbsp;<a href="/GDrive/Delete?file=' + location + '" onclick="return confirm(\'Are you sure you want to delete this file?\');"><i class="fa fa-remove fa-1_3x"></i></a></div>';
                }
                else {
                    var link = '';
                    var folders = location.split('/');
                    for (var j = 0; j < folders.length; j++) {
                        link = folders[0];
                        for (var k = 1; k <= j; k++) {
                            link += '\\\\' + folders[k];
                        }
                    }
                    displayContents = '<a href="' + link.replace(/\\\\/g, "/") + '" onclick="LoadFiles(\'' + link + '\'); return false;">' + file + '</a>';
                }

                html += '<div class="list-group-item"><div style="width: 72%; display: inline-block">';
                html += (i + 1) + '.&nbsp; ' + displayContents + '&nbsp;</div>';
                html += actionContents + '</div>';
            }

            $("#list-of-files").html(html);

            if (data.length > 0) {
                var navigationLinks = '';
                var location = data[0].substring(data[0].indexOf("DriveContents") + 14).replace(/\\/g, "/");
                var folders = location.split('/');
                for (var j = 0; j < folders.length - 1; j++) {
                    var link = folders[0];
                    for (var k = 1; k <= j; k++) {
                        link += '\\\\' + folders[k];
                    }
                    navigationLinks += '&nbsp;/&nbsp;<a href="' + link.replace(/\\\\/g, "/") + '" onclick="LoadFiles(\'' + link + '\'); return false;">' + folders[j] + '</a>';
                }
                $("#navigation").html(navigationLinks);
            }
        }
    </script>
}