Web Framework/WebFramework/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using log4net;
using Ninject;
using System.Configuration;
using WebFramework.Helpers;
using WebFramework.Models.Products;
using WebFramework.Persistence.Products;

namespace WebFramework.Controllers
{
    public class DashboardController : BaseController
    {
        private readonly ILog _log;

        private readonly IProductsDbContext _db;

        public DashboardController([Named(Constants.ServerLoggerName)] ILog log, IProductsDbContext db)
            : base(log)
        {
            _log = log;
            _db = db;
        }

        public ActionResult ComingUp()
        {
            return View("~/Views/Home/About.cshtml");
        }

        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        public ActionResult Remove()
        {
            throw new NotImplementedException("This message is from the exception. This exception has an inner exception.",
                new Exception("This message is from the inner exception. This inner exception has a further inner exception.",
                    new Exception("This message is from the second-level inner exception. This inner exception has no further inner exceptions.")));
        }

        public ActionResult List()
        {
            var list = _db.Items.ToList();
            ViewBag.ListCount = list.Count;

            return View(list);
        }

        public ActionResult Details(int id = 0)
        {
            Item model = _db.Items.Find(id);
            if (model == null)
            {
                return HttpNotFound();
            }

            var list = _db.Items.ToList();
            ViewBag.ListCount = list.Count;

            return View(model);
        }

        public ActionResult Create()
        {
            var list = _db.Items.ToList();
            ViewBag.ListCount = list.Count;

            return View();
        }

        [HttpPost]
        public ActionResult Create(Item model)
        {
            if (ModelState.IsValid)
            {
                model.CreatedOn = DateTime.Now;

                _db.Items.Add(model);
                _db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(model);
        }

        public ActionResult Edit(int id = 0)
        {
            Item model = _db.Items.Find(id);
            if (model == null)
            {
                return HttpNotFound();
            }

            var list = _db.Items.ToList();
            ViewBag.ListCount = list.Count;

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(Item model)
        {
            if (ModelState.IsValid)
            {
                _db.Entry(model).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(model);
        }

        public ActionResult Delete(int id = 0)
        {
            Item model = _db.Items.Find(id);
            if (model == null)
            {
                return HttpNotFound();
            }

            var list = _db.Items.ToList();
            ViewBag.ListCount = list.Count;

            return View(model);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Item model = _db.Items.Find(id);
            _db.Items.Remove(model);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Web Framework/WebFramework/Controllers/DemosController.cs
namespace WebFramework.Controllers
{
    using log4net;
    using Ninject;
    using System;
    using System.Web.Mvc;
    using WebFramework.Helpers;
    using WebFramework.ViewModels;

    public class DemosController : BaseController
    {
        private readonly ILog _log;

        public DemosController([Named(Constants.ServerLoggerName)] ILog log)
            : base(log)
        {
            _log = log;
        }

        public ActionResult Index()
        {
            return View();
        }
    }
}

Web Framework/WebFramework/Controllers/EcommerceController.cs
namespace WebFramework.Controllers
{
    using log4net;
    using Ninject;
    using System;
    using System.Linq;
    using System.Web.Mvc;
    using WebFramework.Helpers;
    using WebFramework.Persistence.Products;
    using WebFramework.ViewModels;

    public class EcommerceController : BaseController
    {
        private readonly ILog _log;

        public EcommerceController([Named(Constants.ServerLoggerName)] ILog log)
            : base(log)
        {
            _log = log;
        }

        public ActionResult Index()
        {
            return View((object)Api.EcommerceController.GetBaseUrl());
        }
    }
}

Web Framework/WebFramework/Controllers/GDriveController.cs
namespace WebFramework.Controllers
{
    using log4net;
    using Microsoft.AspNet.Identity;
    using Microsoft.Owin.Security;
    using Ninject;
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Security.Claims;
    using System.Web;
    using System.Web.Mvc;
    using WebFramework.App_Start;
    using WebFramework.Helpers;
    using WebFramework.Persistence.GDrive;

    [SecurityCode]
    public class GDriveController : BaseController
    {
        private readonly ILog _log;

        private readonly IGDriveDbContext _db;

        public GDriveController([Named(WebFramework.Helpers.Constants.ServerLoggerName)] ILog log, IGDriveDbContext db)
            : base(log)
        {
            _log = log;
            _db = db;
        }

        public ActionResult Index()
        {
            ViewBag.MaxNoOfFiles = ConfigManager.Get<string>("MaxNoOfFiles");
            ViewBag.MaxFileSize = ConfigManager.Get<decimal>("MaxFileSizeInMB");
            ViewBag.DriveFileFormats = ConfigManager.Get<string>("DriveFileFormats");

            return View();
        }

        [HttpPost]
        public ActionResult Index(System.Web.HttpPostedFileBase file)
        {
            var maxNoOfFiles = ConfigManager.Get<int>("MaxNoOfFiles");
            var maxFileSize = ConfigManager.Get<decimal>("MaxFileSizeInMB");
            var driveFileFormats = ConfigManager.Get<string>("DriveFileFormats");
            ViewBag.MaxNoOfFiles = maxNoOfFiles;
            ViewBag.MaxFileSize = maxFileSize;
            ViewBag.DriveFileFormats = driveFileFormats;

            var msg = string.Empty;
            if (file != null && file.ContentLength > 0)
            {
                try
                {
                    var formats = driveFileFormats.Split(new[] { "," }, StringSplitOptions.RemoveEmptyEntries).ToList();
                    var ext = file.FileName.Substring(file.FileName.LastIndexOf('.') + 1);

                    var identity = (ClaimsIdentity)User.Identity;
                    var claimsUserData = identity.Claims.FirstOrDefault(a => a.Type == "http://schemas.microsoft.com/ws/2008/06/identity/claims/userdata");
                    var superUser = false;
                    if (claimsUserData != null && claimsUserData.Value == ConfigManager.Get<string>("SecretSecurityCode"))
                    {
                        superUser = true;
                    }

                    var fileSize = ((decimal)file.ContentLength) / 1024.0m / 1024.0m; // in MB.
                    if (!superUser && fileSize > maxFileSize)
                    {
                        msg = "Selected file (" + fileSize.ToString("0.00") + "MB) is exceeding the limit.";
                    }
                    else if (!superUser && !formats.Any(a => a.Trim().Equals(ext, StringComparison.CurrentCultureIgnoreCase)))
                    {
                        msg = ext.ToUpper() + " file format is not accepted.";
                    }
                    else if (!superUser && GetNoOfFiles() > maxNoOfFiles)
                    {
                        msg = "You have reached your quota of files.";
                    }
                    else if (_db.Files.FirstOrDefault(f => f.FileName == file.FileName) != null)
                    {
                        msg = "File with same name already exists.";
                    }
                    else if (claimsUserData == null)
                    {
                        msg = "Unable to read your security code. Logout and log back in please.";
                    }
                    else
                    {
                        byte[] fileData = null;
                        using (var binaryReader = new BinaryReader(Request.Files[0].InputStream))
                        {
                            fileData = binaryReader.ReadBytes(Request.Files[0].ContentLength);
                        }
                        if (fileData == null || fileData.Length == 0)
                        {
                            return RedirectToAction("Index");
                        }

                        _db.Files.Add(new Models.GDrive.FileContent
                                                {
                                                    SecurityCode = claimsUserData.Value,
                                                    FileName = file.FileName,
                                                    UploadedOn = DateTime.Now,
                                                    Content = fileData
                                                });
                        _db.SaveChanges();

                        IncrementNoOfFiles();

                        Session["USER_MESSAGE"] = "Your file has been successfully uploaded.";
                        Session["USER_MESSAGE_SEVERITY"] = "Success";
                        Session["USER_MESSAGE_TITLE"] = "File Uploaded";

                        return RedirectToAction("Index");
                    }
                }
                catch (Exception ex)
                {
                    _log.Error("GDrive Upload", ex);
                    msg = "Sorry, an error occured while uploading your file. Please try again.";
                }
            }
            else
            {
                msg = "You have not specified a file.";
            }

            Session["USER_MESSAGE"] = msg;
            Session["USER_MESSAGE_SEVERITY"] = "Error";

            return RedirectToAction("Index");
        }

        public ActionResult Download(string file)
        {
            var fileContent = _db.Files.FirstOrDefault(f => f.FileName == file);
            if (fileContent == null)
            {
                Session["USER_MESSAGE"] = "File not found.";
                Session["USER_MESSAGE_SEVERITY"] = "Error";
                Session["USER_MESSAGE_TITLE"] = "File not found";

                return RedirectToAction("Index");
            }

            return File(fileContent.Content, GetContentType(fileContent.FileName));
        }

        public ActionResult Delete(string file)
        {
            if (!string.IsNullOrWhiteSpace(file))
            {
                var fileContent = _db.Files.FirstOrDefault(f => f.FileName == file);
                if (fileContent == null)
                {
                    Session["USER_MESSAGE"] = "File not found.";
                    Session["USER_MESSAGE_SEVERITY"] = "Error";
                    Session["USER_MESSAGE_TITLE"] = "File not found";

                    return RedirectToAction("Index");
                }

                _db.Files.Remove(fileContent);
                _db.SaveChanges();

                DecrementNoOfFiles();

                Session["USER_MESSAGE"] = "The file has been successfully deleted.";
                Session["USER_MESSAGE_SEVERITY"] = "Success";
                Session["USER_MESSAGE_TITLE"] = "File Deleted";

                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
        }

        public JsonResult GetFiles(string folder)
        {
            var identity = (ClaimsIdentity)User.Identity;
            var claimsUserData = identity.Claims.FirstOrDefault(a => a.Type == "http://schemas.microsoft.com/ws/2008/06/identity/claims/userdata");
            var t = _db.Files.Where(w => w.SecurityCode == claimsUserData.Value).Select(s => s.FileName).ToList();
            return new JsonResult { Data = t, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        private string GetContentType(string fileName)
        {
            var ext = fileName.Substring(fileName.LastIndexOf('.') + 1).ToUpper();
            switch (ext)
            {
                case "JPG":
                case "JPEG":
                    return "image/jpeg";

                case "PNG":
                    return "image/png";

                case "ZIP":
                    return "application/zip";

                default:
                    return string.Empty;
            }
        }

        private int GetNoOfFiles()
        {
            var cookie = Request.Cookies["NO_OF_FILES"];
            if (cookie != null)
            {
                var noOfFiles = 0;
                var value = cookie.Value ?? string.Empty;
                if (int.TryParse(value, out noOfFiles))
                {
                    return noOfFiles;
                }
            }

            return 0;
        }

        private void IncrementNoOfFiles()
        {
            var noOfFiles = GetNoOfFiles();
            var nextFileAt = DateTime.Now.Add(TimeSpan.FromMinutes(300));

            var cookie = new HttpCookie("NO_OF_FILES", (++noOfFiles).ToString());
            cookie.Expires = nextFileAt;
            Response.Cookies.Add(cookie);

            var expiry = new HttpCookie("NEXT_FILE_AT", nextFileAt.ToString());
            expiry.Expires = nextFileAt;
            Response.Cookies.Add(expiry);
        }

        private void DecrementNoOfFiles()
        {
            var noOfFiles = GetNoOfFiles();
            var nextFileAt = DateTime.Now.Add(TimeSpan.FromMinutes(300));

            var cookie = new HttpCookie("NO_OF_FILES", (--noOfFiles).ToString());
            cookie.Expires = nextFileAt;
            Response.Cookies.Add(cookie);

            var expiry = new HttpCookie("NEXT_FILE_AT", nextFileAt.ToString());
            expiry.Expires = nextFileAt;
            Response.Cookies.Add(expiry);
        }
    }
}

Web Framework/WebFramework/Views/Demos/Index.cshtml
@{
    ViewBag.Title = "Demos";
}

@section breadcrumbs {
    <ol class="breadcrumb">
        <li><a href="@Url.Action("Index", "Home")"><i class="fa fa-home fa-1_3x"></i></a></li>
        <li><a href="/Demos#demo-selection" onclick="return LoadContent('#demo-selection');">Demos</a></li>
    </ol>
}

<div id="demo-area">
</div>

<div class="demo-content">
    <script type="text/html" id="angular">
        @Html.Partial("_angular")
    </script>

    <script type="text/html" id="bootstrap">
        @Html.Partial("_bootstrap")
    </script>

    <script type="text/html" id="jasmine">
        @Html.Partial("_jasmin")
    </script>

    <script type="text/html" id="type-js">
        @Html.Partial("_type-js")
    </script>

    <script type="text/html" id="sass-less">
        @Html.Partial("_sass-less")
    </script>

    <script type="text/html" id="bower-npm">
        @Html.Partial("_bower-npm")
    </script>

    <script type="text/html" id="git-gulp">
        @Html.Partial("_git-gulp")
    </script>

    <script type="text/html" id="knockout">
        @Html.Partial("_knockout")
    </script>

    <script type="text/html" id="font-awesome">
        @Html.Partial("_font-awesome")
    </script>

    <script type="text/html" id="jshint">
        @Html.Partial("_jshint")
    </script>

    <script type="text/html" id="demo-selection">
        <section>
            <ul>
                <li><a href="/Demos#bootstrap" onclick="return LoadContent('#bootstrap');">Bootstrap</a></li>
                <li><a href="/Demos#jasmine" onclick="return LoadContent('#jasmine');">Jasmine Test</a></li>
                <li><a href="/Demos#sass-less" onclick="return LoadContent('#sass-less');">Sass &amp; Scss</a></li>
                <li><a href="/Demos#jshint" onclick="return LoadContent('#jshint');">JSHint</a></li>
                <li><a href="/Demos#bower-npm" onclick="return LoadContent('#bower-npm');">npm &amp; Bower</a></li>
                <li><a href="/Demos#git-gulp" onclick="return LoadContent('#git-gulp');">Git &amp; Gulp</a></li>
                <li><a href="/Demos#angular" onclick="return LoadContent('#angular');">Angular JS</a></li>
                <li><a href="/Demos#knockout" onclick="return LoadContent('#knockout');">Knockout JS</a></li>
                <li><a href="/Demos#font-awesome" onclick="return LoadContent('#font-awesome');">Font Awesome</a></li>
                <li><a href="/Demos#type-js" onclick="return LoadContent('#type-js');">Type Script</a></li>
            </ul>
        </section>
    </script>

</div>

@section pageStyle {
    <style type="text/css">
        pre {
            display: inline-block;
        }
    </style>
}

@section pageScript {
    <script type="text/javascript">
        function LoadContent(id) {
            var html = $(id).html();
            $("#demo-area").html(html);
            window.scrollTo(0, 0);
            return true;
        }

        RegisterOnload(function () {
            var id = window.location.hash;
            if (id) {
                LoadContent(id);
            }
            else {
                LoadContent('#demo-selection');
            }
        });
    </script>
}

Web Framework/WebFramework/Views/Demos/_angular.cshtml
<section>
    <h3>Angular JS</h3>
    <hr />
    <p>
        @Html.ActionLink("eCommerce", "Index", "Ecommerce", new { area = "" }, new { target = "_blank" }) feature is developed using Angular JS.
        This page is coming up soon... More info on <a href="https://docs.angularjs.org/guide" target="_blank">AngularJs</a>&nbsp;<span class="glyphicon glyphicon-new-window"></span>.
    </p>
</section>

Web Framework/WebFramework/Views/Demos/_bootstrap.cshtml
<section>
    <h3>Bootstrap</h3>
    <hr />
    <p>
        <i class="fa fa-chevron-circle-right"></i>&nbsp;&nbsp;Header dropdown menu (<code>.navbar-inverse</code> theme) is customized to feature <strong>multi-level dropdown menu</strong> options on hover.
    </p>
    <p>
        <i class="fa fa-chevron-circle-right"></i>&nbsp;&nbsp;
        Custom alert implementation using <strong>Modal</strong> feature with <strong>Panel</strong> elements. Sample alerts:
        <a href="#" onclick="alertify('A status message to demonstrate this simple popup.', 'Success'); return false;">success</a>,
        <a href="#" onclick="alertify('A status message to demonstrate this simple popup.', 'Error'); return false;">error</a>, &
        <a href="#" onclick="alertify('A status message to demonstrate this simple popup.', 'Info', 'Custom title here'); return false;">info</a>.
    </p>
    <p>
        <i class="fa fa-chevron-circle-right"></i>&nbsp;&nbsp;Features like Navbars & Breadcrumbs,
        @Html.ActionLink("Carousel", "Index", "Dashboard", null, new { target = "_blank" }) &
        @Html.ActionLink("Jumbotron", "Index", "Home", null, new { target = "_blank" }) (demo buttons container),
        collapsable @Html.ActionLink("Accordion", "Index", "Home", null, new { target = "_blank" }) &
        @Html.ActionLink("List groups", "Index", "GDrive", null, new { target = "_blank" }) (needs signing in),
        <a href="#" onclick="alertify('An alert using Panels (.panel, .panel-heading, .panel-body).', 'Success', 'Basic example of panels'); return false;">Panels</a> &
        @Html.ActionLink("Badges", "AllPosts", "Blog", null, new { area = "Blog", target = "_blank" }), etc.
        are all used where appropriate.
    </p>
    <p>
        <i class="fa fa-chevron-circle-right"></i>&nbsp;&nbsp;Bootstrap (and many other 3<sup>rd</sup> party libraries) optimally loaded via <strong>CDN securely</strong> (using TLS & <a href="https://www.srihash.org/" target="_blank">SRI Hash</a>), with any <strong>customizations made locally</strong> extending their LESS source code.
    </p>
    <p>
        <i class="fa fa-chevron-circle-right"></i>&nbsp;&nbsp;<strong>Fallback mechanism</strong> for Bootstrap CDN is acheived by checking if the below element is visible, and loading vanilla Bootstrap CSS from local hosting server if so.
        <br />
        <pre><span style="color: blue">&lt;</span><span style="color: maroon">div</span> <span style="color: red">id</span>=<span style="color: blue">"bootstrap-cdn-down"</span> <span style="color: red">class</span>=<span style="color: blue">"hidden"&gt;</span><span style="color: blue">&lt;/</span><span style="color: maroon">div</span><span style="color: blue">&gt;</span> <span style="color: green">&lt;!-- Make sure you do NOT define a "hidden" style changing visibility! --&gt;</span></pre>
    </p>
    <p>
        <i class="fa fa-chevron-circle-right"></i>&nbsp;&nbsp;
        New <strong>custom buttons</strong> added:
        <span class="btn btn-custom-black btn-xs">btn-custom-black</span>
        <span class="btn btn-custom-failure btn-xs">btn-custom-failure</span>
        <span class="btn btn-custom-default btn-md">btn-custom-default</span>
        <span class="btn btn-custom-metallic btn-md">btn-custom-metallic</span>
        <span class="btn btn-custom-success btn-lg">btn-custom-success</span>
    </p>
    <p>
        <i class="fa fa-chevron-circle-right"></i>&nbsp;&nbsp;
        Complete <strong>vanilla Bootstrap</strong> retained, including buttons:
        <span class="btn btn-danger btn-md">btn-danger</span>
        <span class="btn btn-warning btn-md">btn-warning</span>
        <span class="btn btn-default btn-md">btn-default</span>
        <span class="btn btn-info btn-md">btn-info</span>
        <span class="btn btn-primary btn-md">btn-primary</span>
        <span class="btn btn-success btn-md">btn-success</span>
    </p>
    <p>
        <i class="fa fa-chevron-circle-right"></i>&nbsp;&nbsp;
        <strong>Responsiveness</strong>:
        <br />
        <div style="padding-left: 50px;">
            <div style="padding: 20px 0">
                <i class="fa fa-circle fa-0_8x"></i> <strong>Mobile View - XS</strong>
                <br />
                <br />
                <img class="img-thumbnail" src="~/Images/Demos/1. Mobile - XS.jpg" alt="Mobile View" title="Mobile View - XS" width="320" />
            </div>
            <div style="padding: 20px 0">
                <i class="fa fa-circle fa-0_8x"></i> <strong>Tablet Portrait - SM</strong>
                <br />
                <br />
                <img class="img-thumbnail" src="~/Images/Demos/2. Tablet - SM.jpg" alt="Tablet Portrait" title="Tablet Portrait - SM" width="768" />
            </div>
            <div style="padding: 20px 0">
                <i class="fa fa-circle fa-0_8x"></i> <strong>Tablet Landscape - MD</strong>
                <br />
                <br />
                <img class="img-thumbnail" src="~/Images/Demos/3. Tablet - MD.jpg" alt="Tablet Landscape" title="Tablet Landscape - MD" width="1024" />
            </div>
            <div style="padding: 20px 0">
                <i class="fa fa-circle fa-0_8x"></i> <strong>Laptop - LG</strong>
                <br />
                <br />
                <img class="img-thumbnail" src="~/Images/Demos/4. Laptop - LG.png" alt="Laptop View" title="Laptop View - LG" width="1280" />
            </div>
        </div>
    </p>
    <p><strong>Happy Inspecting (F12)!</strong></p>
</section>

Web Framework/WebFramework/Views/Demos/_bower-npm.cshtml
<section>
    <h3>npm - Never Program Mad</h3>
    <hr />
    <p>
        <i class="fa fa-chevron-circle-right"></i>&nbsp;&nbsp;First things first - Node Package Manager (npm) command-line tool is bundled with Node.js. If you have it installed, then you already have npm too. If not, go download Node.js.
    </p>
    <p>
        <i class="fa fa-chevron-circle-right"></i>&nbsp;&nbsp;Ensure you have installed correctly:
<pre>
$ node --version
$ npm --version
</pre>
    </p>
    <h3>Bower - Another Package Manager</h3>
    <hr />
    <p>
        <i class="fa fa-chevron-circle-right"></i>&nbsp;&nbsp;Bower requires Node, npm &amp; Git. Once you have it, get started:
<pre>
$ npm install -g bower
</pre>
    </p>
    <p>
        <i class="fa fa-chevron-circle-right"></i>&nbsp;&nbsp;Bower installs packages to <i>bower_components/</i> folder. A package can be a GitHub shorthand, a Git endpoint, a URL, local folder, and more. Find out more <a href="https://bower.io/docs/api/" target="_blank">here</a>&nbsp;<span class="glyphicon glyphicon-new-window"></span>.
    </p>
    <p>
        <i class="fa fa-chevron-circle-right"></i>&nbsp;&nbsp;Typical <i>bower.json</i>:
<pre>
{
  "name": "angular-phonecat",
  "description": "A starter project for AngularJS",
  "version": "0.0.0",
  "homepage": "https://github.com/angular/angular-phonecat",
  "license": "MIT",
  "private": true,
  "dependencies": {
    "angular": "1.5.x",
    "angular-animate": "1.5.x",
    "angular-mocks": "1.5.x",
    "angular-resource": "1.5.x",
    "angular-route": "1.5.x",
    "bootstrap": "3.3.x",
    "jquery": "2.2.x"
  }
}
</pre>
    </p>
    <p>
        <i class="fa fa-chevron-circle-right"></i>&nbsp;&nbsp;Back to npm, a typical <i>package.json</i>:
<pre>
{
  "name": "angular-phonecat",
  "private": true,
  "version": "0.0.0",
  "description": "A tutorial application for AngularJS",
  "repository": "https://github.com/angular/angular-phonecat",
  "license": "MIT",
  "devDependencies": {
    "bower": "^1.7.7",
    "http-server": "^0.9.0",
    "jasmine-core": "^2.4.1",
    "karma": "^0.13.22",
    "karma-chrome-launcher": "^0.2.3",
    "karma-firefox-launcher": "^0.1.7",
    "karma-jasmine": "^0.3.8",
    "protractor": "^3.2.2"
  },
  "scripts": {
    "postinstall": "bower install",

    "prestart": "npm install",
    "start": "http-server ./app -a localhost -p 8000 -c-1",

    "pretest": "npm install",
    "test": "karma start karma.conf.js",
    "test-single-run": "karma start karma.conf.js --single-run",

    "preupdate-webdriver": "npm install",
    "update-webdriver": "webdriver-manager update",

    "preprotractor": "npm run update-webdriver",
    "protractor": "protractor e2e-tests/protractor.conf.js",
  }
}
</pre>
    </p>
</section>

Web Framework/WebFramework/Views/Demos/_font-awesome.cshtml
<section>
    <h3>Font Awesome</h3>
    <hr />
    <p>
        Icons in this website are from Font Awesome. This page is coming up soon... More info <a href="http://fontawesome.io/" target="_blank">here</a>&nbsp;<span class="glyphicon glyphicon-new-window"></span>.
    </p>
</section>

Web Framework/WebFramework/Views/Demos/_jshint.cshtml
<section>
    <h3>Javascript Linting</h3>
    <hr />
    <p>
        <i class="fa fa-chevron-circle-right"></i>&nbsp;&nbsp;Getting started:
        <pre>
npm install -g jshint
npm install --save-dev jshint :: As a development dependency within a project.
        </pre>
    </p>
    <p>
        <i class="fa fa-chevron-circle-right"></i>&nbsp;&nbsp;Lint a specific file:
        <pre>jshint product-list/product-list.component.js</pre>
    </p>
    <p>
        <i class="fa fa-chevron-circle-right"></i>&nbsp;&nbsp;Specifying a config file explicitly:
        <pre>jshint --config ../path/to/my/config.json</pre>
    </p>
    <p>
        <i class="fa fa-chevron-circle-right"></i>&nbsp;&nbsp;Some configs that can be used in your config in JSON format: curly, eqeqeq, maxdepth, strict, undef, unused, eqnull, browser, devel, jasmine, jquery, node, qunit
    </p>
    <p>
        <i class="fa fa-chevron-circle-right"></i>&nbsp;&nbsp;Some linting CLI options:
        <pre>jshint --reporter=checkstyle --verbose --exclude-path=../test myfile.js</pre>
    </p>
    <p>
        <i class="fa fa-chevron-circle-right"></i>&nbsp;&nbsp;Some inline linting:
<pre>
/* jshint strict: true, vars: true, unused:true, eqnull:true */
/* globals MY_LIB: false */ -- read-only
/* globals -BAD_LIB */ -- black list
/* jshint ignore:start */
/* jshint ignore:end */
// jshint ignore:line
/* falls through */ -- switch statement cases
</pre>
    </p>
    <p>
        <i class="fa fa-chevron-circle-right"></i>&nbsp;&nbsp;Typical <i>.jshintrc</i> file:
<pre>
{
  "strict": "global",
  "globals": {

    // Angular
    "angular": false,

    // Angular mocks
    "module": false,
    "inject": false,

    // Jasmine
    "jasmine": false,
    "describe": false,
    "beforeEach": false,
    "afterEach": false,
    "it": false,
    "expect": false,

    // Protractor
    "browser": false,
    "element": false,
    "by": false
  }
}
</pre>
    </p>
</section>

Web Framework/WebFramework/Views/Demos/_type-js.cshtml
<section>
    <h3>Type Script</h3>
    <hr />
    <p>
        Coming up soon... More info <a href="https://www.typescriptlang.org/docs/tutorial.html" target="_blank">here</a>&nbsp;<span class="glyphicon glyphicon-new-window"></span>.
    </p>
</section>