Web Framework/WebFramework/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using log4net;
using Ninject;
using System.Configuration;
using WebFramework.Helpers;
using WebFramework.Models.Products;
using WebFramework.Persistence.Products;

namespace WebFramework.Controllers
{
    public class DashboardController : BaseController
    {
        private readonly ILog _log;

        private readonly IProductsDbContext _db;

        public DashboardController([Named(Constants.ServerLoggerName)] ILog log, IProductsDbContext db)
            : base(log)
        {
            _log = log;
            _db = db;
        }

        public ActionResult ComingUp()
        {
            return View("~/Views/Home/About.cshtml");
        }

        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        public ActionResult Remove()
        {
            throw new NotImplementedException("This message is from the exception. This exception has an inner exception.",
                new Exception("This message is from the inner exception. This inner exception has a further inner exception.",
                    new Exception("This message is from the second-level inner exception. This inner exception has no further inner exceptions.")));
        }

        public ActionResult List()
        {
            var list = _db.Items.ToList();
            ViewBag.ListCount = list.Count;

            return View(list);
        }

        public ActionResult Details(int id = 0)
        {
            Item model = _db.Items.Find(id);
            if (model == null)
            {
                return HttpNotFound();
            }

            var list = _db.Items.ToList();
            ViewBag.ListCount = list.Count;

            return View(model);
        }

        public ActionResult Create()
        {
            var list = _db.Items.ToList();
            ViewBag.ListCount = list.Count;

            return View();
        }

        [HttpPost]
        public ActionResult Create(Item model)
        {
            if (ModelState.IsValid)
            {
                model.CreatedOn = DateTime.Now;

                _db.Items.Add(model);
                _db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(model);
        }

        public ActionResult Edit(int id = 0)
        {
            Item model = _db.Items.Find(id);
            if (model == null)
            {
                return HttpNotFound();
            }

            var list = _db.Items.ToList();
            ViewBag.ListCount = list.Count;

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(Item model)
        {
            if (ModelState.IsValid)
            {
                _db.Entry(model).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(model);
        }

        public ActionResult Delete(int id = 0)
        {
            Item model = _db.Items.Find(id);
            if (model == null)
            {
                return HttpNotFound();
            }

            var list = _db.Items.ToList();
            ViewBag.ListCount = list.Count;

            return View(model);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Item model = _db.Items.Find(id);
            _db.Items.Remove(model);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Web Framework/WebFramework/Controllers/DemosController.cs
namespace WebFramework.Controllers
{
    using log4net;
    using Ninject;
    using System;
    using System.Web.Mvc;
    using WebFramework.Helpers;
    using WebFramework.ViewModels;

    public class DemosController : BaseController
    {
        private readonly ILog _log;

        public DemosController([Named(Constants.ServerLoggerName)] ILog log)
            : base(log)
        {
            _log = log;
        }

        public ActionResult Index()
        {
            return View();
        }
    }
}

Web Framework/WebFramework/Controllers/EcommerceController.cs
namespace WebFramework.Controllers
{
    using log4net;
    using Ninject;
    using System;
    using System.Linq;
    using System.Web.Mvc;
    using WebFramework.Helpers;
    using WebFramework.Persistence.Products;
    using WebFramework.ViewModels;

    public class EcommerceController : BaseController
    {
        private readonly ILog _log;

        public EcommerceController([Named(Constants.ServerLoggerName)] ILog log)
            : base(log)
        {
            _log = log;
        }

        public ActionResult Index()
        {
            return View((object)Api.EcommerceController.GetBaseUrl());
        }
    }
}

Web Framework/WebFramework/Views/Shared/_alertMessage.cshtml
<!-- Modal alert -->
<div id="alertify-msg" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="alertMsgModalLabel">
    <div class="modal-dialog" role="document">
        <div class="panel">
            <div class="panel-heading">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="opacity: 0.5"><i class="fa fa-times-circle"></i></button>
                <h4 class="panel-title text-uppercase"><i></i>&nbsp;&nbsp;<span></span></h4>
            </div>
            <div class="panel-body">
                <div class="alertify-content" style="min-height: 75px; max-height: 300px; overflow-y: auto; padding-top: 15px">
                </div>
                <div style="text-align: center">
                    <span class="alertify-footer" data-dismiss="modal">CLOSE</span>
                </div>
            </div>
        </div>
    </div>
</div>

Web Framework/WebFramework/Views/Shared/_commonLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title - GuruIn.NET</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />

    <meta name="description" content="Guru In .NET or .NET guru is a website developed to highlight some key aspects of web development using .NET framework." />
    <meta name="keywords" content=".NET, guru, guru in .NET, @ViewBag.Keywords" />
    <meta name="robots" content="noindex, follow" />
    @*<meta http-equiv="refresh" content="3; url=@ViewBag.RefreshUrl" />*@

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" integrity="sha384-XdYbMnZ/QjLh6iI4ogqCTaIjrFk87ip+ekIjefZch0Y+PvJ8CDYtEs1ipDmPorQ+" crossorigin="anonymous">
    @Styles.Render("~/bundles/centered-layout-css")
    @RenderSection("pageStyle", required: false)
    <!--[if lt IE 9]>
      <script src="/Content/jQuery/html5shiv.min.js"></script>
      <script src="/Content/jQuery/respond.min.js"></script>
    <![endif]-->
</head>
<body class="container-fluid" style="font-family: Verdana, Arial, sans-serif">
    @{
        var isDebugMode = "False";
        if (TempData.Keys.Contains("IsDebugMode") && TempData["IsDebugMode"] != null)
        {
            isDebugMode = TempData["IsDebugMode"].ToString();
        }
    }
    <input id="is-debug-mode" type="hidden" value="@isDebugMode" />

    @{
        var msg = "";
        var severity = "Info";
        var title = "";
        if (TempData.Keys.Contains("UserMessage") && TempData["UserMessage"] != null)
        {
            msg = TempData["UserMessage"].ToString();
            if (TempData.Keys.Contains("UserMessageSeverity") && TempData["UserMessageSeverity"] != null)
            {
                severity = TempData["UserMessageSeverity"].ToString();
            }

            if (TempData.Keys.Contains("UserMessageTitle") && TempData["UserMessageTitle"] != null)
            {
                title = TempData["UserMessageTitle"].ToString();
            }
        }
    }
    <input id="user-message" type="hidden" value="@msg" />
    <input id="user-message-severity" type="hidden" value="@severity" />
    <input id="user-message-title" type="hidden" value="@title" />

    <div id="bootstrap-cdn-down" class="hidden"></div>
    <noscript>Please enable Javascript (<a href="http://enable-javascript.com/" title="Instructions to enable Javascript" target="_blank">help</a>).</noscript>
    @Html.Partial("_jsErrorAlert")
    @Html.Partial("_workInProgress")
    @Html.Partial("_alertMessage")


    <div class="row no-spacing">
        <header class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <nav class="navbar navbar-inverse navbar-fixed-top">
                @Html.Partial("_headerMenu")
            </nav>
            <section class="breadcrumbs-container">
                <div class="container">
                    @RenderSection("breadcrumbs", required: true)
                </div>
            </section>
        </header>

        <main class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <section id="main-content" class="container">
                <div style="margin-bottom: 50px; position: relative">
                    @RenderBody()
                </div>
            </section>
            <div class="clearfix"></div>
            <section class="footer-menu hidden-xs col-lg-12 col-md-12 col-sm-12">
                <div class="container">
                    @Html.Partial("_footerMenu")
                </div>
            </section>
        </main>

        <footer class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="footer text-center">
                @Html.Partial("_copyrightAndVersion")
            </div>
        </footer>
    </div>

    <script src="https://code.jquery.com/jquery-2.2.1.min.js" integrity="sha256-gvQgAFzTH6trSrAWoH1iPo9Xc96QxSZ3feW6kem+O00=" crossorigin="anonymous"></script>
    <script>(window.jQuery || document.write('<script src="/Content/jQuery/jquery-2.2.1.min.js"><\/script>'));</script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    <script>($.fn.modal || document.write('<script src="/Content/Bootstrap/js/bootstrap.min.js"><\/script>'));</script>
    @Scripts.Render("~/bundles/centered-layout-js")
    @RenderSection("pageScript", required: false)

</body>
</html>

Web Framework/WebFramework/Views/Shared/_copyrightAndVersion.cshtml
<p>&copy; @DateTime.Now.Year - GuruIn.NET - V<span>@TempData["VersionInfo"]</span></p>

Web Framework/WebFramework/Views/Shared/_exceptionDetails.cshtml
@model System.Exception

<div>
    @if (Model != null && !string.IsNullOrWhiteSpace(Model.Message))
    {
        <h4>Exception Message:</h4>
        <h6>@Model.Message</h6>
    }

    @if (Model.InnerException != null && !string.IsNullOrWhiteSpace(Model.InnerException.Message))
    {
        <h5 style="padding-left: 15px">Inner Exception Message:</h5>
        <h6 style="padding-left: 15px">@Model.InnerException.Message</h6>
        @Html.HiddenFor(model => model.InnerException.Message)
    }

    @if (Model.InnerException != null && Model.InnerException.InnerException != null && !string.IsNullOrWhiteSpace(Model.InnerException.InnerException.Message))
    {
        <h5 style="padding-left: 30px">2<sup>nd</sup> Level Inner Exception Message:</h5>
        <h6 style="padding-left: 30px">@Model.InnerException.InnerException.Message</h6>
    }

    @if (Model != null && !string.IsNullOrWhiteSpace(Model.StackTrace))
    {
        <p><b>Stack Trace:</b></p>
        <div style="padding-bottom: 30px; max-height: 350px; overflow-y: auto">
            @{ var stackTrace = Model.StackTrace.Split(new[] { " at " }, StringSplitOptions.RemoveEmptyEntries); }
            @for (var i = 1; i < stackTrace.Count(); i++)
            {
                <div><code>@i: @stackTrace[i]</code></div>
            }
        </div>
    }

    @if (Model != null && !string.IsNullOrWhiteSpace((string)Model.Data["stackTrace"]))
    {
        <p><b>Stack Trace:</b></p>
        <div style="padding-bottom: 30px; max-height: 350px; overflow-y: auto">
            @{ var stackTrace = ((string)Model.Data["stackTrace"]).Split(new[] { " at " }, StringSplitOptions.RemoveEmptyEntries); }
            @for (var i = 1; i < stackTrace.Count(); i++)
            {
                <div><code>@i: @stackTrace[i]</code></div>
            }
        </div>
    }

    @if (Model == null ||
            (string.IsNullOrWhiteSpace(Model.StackTrace) &&
            string.IsNullOrWhiteSpace((string)Model.Data["stackTrace"])))
    {
        <div style="min-height: 350px"></div>
    }
</div>

Web Framework/WebFramework/Views/Shared/_filterLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title - GuruIn.NET</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />

    <meta name="description" content="Guru In .NET or .NET guru is a website developed to highlight some key aspects of web development using .NET framework." />
    <meta name="keywords" content=".NET, guru, guru in .NET, @ViewBag.Keywords" />
    <meta name="robots" content="noindex, follow" />

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" integrity="sha384-XdYbMnZ/QjLh6iI4ogqCTaIjrFk87ip+ekIjefZch0Y+PvJ8CDYtEs1ipDmPorQ+" crossorigin="anonymous">
    @Styles.Render("~/bundles/submenu-layout-css")
    @RenderSection("pageStyle", required: false)
    <!--[if lt IE 9]>
      <script src="/Content/jQuery/html5shiv.min.js"></script>
      <script src="/Content/jQuery/respond.min.js"></script>
    <![endif]-->
</head>
<body class="container-fluid" style="font-family: Verdana, Arial, sans-serif; padding-left: 0">
    @{
        var isDebugMode = "False";
        if (TempData.Keys.Contains("IsDebugMode") && TempData["IsDebugMode"] != null)
        {
            isDebugMode = TempData["IsDebugMode"].ToString();
        }
    }
    <input id="is-debug-mode" type="hidden" value="@isDebugMode" />

    @{
        var msg = "";
        var severity = "Info";
        var title = "";
        if (TempData.Keys.Contains("UserMessage") && TempData["UserMessage"] != null)
        {
            msg = TempData["UserMessage"].ToString();
            if (TempData.Keys.Contains("UserMessageSeverity") && TempData["UserMessageSeverity"] != null)
            {
                severity = TempData["UserMessageSeverity"].ToString();
            }

            if (TempData.Keys.Contains("UserMessageTitle") && TempData["UserMessageTitle"] != null)
            {
                title = TempData["UserMessageTitle"].ToString();
            }
        }
    }
    <input id="user-message" type="hidden" value="@msg" />
    <input id="user-message-severity" type="hidden" value="@severity" />
    <input id="user-message-title" type="hidden" value="@title" />

    <div id="bootstrap-cdn-down" class="hidden"></div>
    <noscript>Please enable Javascript (<a href="http://enable-javascript.com/" title="Instructions to enable Javascript" target="_blank">help</a>).</noscript>
    @Html.Partial("_jsErrorAlert")
    @Html.Partial("_workInProgress")
    @Html.Partial("_alertMessage")


    <div class="row no-spacing">
        <header class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <nav class="navbar navbar-inverse navbar-fixed-top">
                @Html.Partial("_headerMenu")
            </nav>
            <section class="breadcrumbs-container">
                <div class="col-lg-offset-2 col-md-offset-3">
                    @RenderSection("breadcrumbs", required: true)
                </div>
            </section>
        </header>

        <main class="col-lg-12 col-md-12 col-sm-12 col-xs-12" style="width: 100%">
            <section class="container" style="float: left; background-color: #333; padding-right: 0; width: 100%">
                <div style="margin-bottom: 50px; position: relative">
                    @RenderBody()
                </div>
            </section>
            <div class="clearfix"></div>
        </main>

        <footer class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="footer text-center">
                @Html.Partial("_copyrightAndVersion")
            </div>
        </footer>
    </div>

    <script src="https://code.jquery.com/jquery-2.2.1.min.js" integrity="sha256-gvQgAFzTH6trSrAWoH1iPo9Xc96QxSZ3feW6kem+O00=" crossorigin="anonymous"></script>
    <script>(window.jQuery || document.write('<script src="/Content/jQuery/jquery-2.2.1.min.js"><\/script>'));</script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    <script>($.fn.modal || document.write('<script src="/Content/Bootstrap/js/bootstrap.min.js"><\/script>'));</script>
    @Scripts.Render("~/bundles/submenu-layout-js")
    @RenderSection("pageScript", required: false)

</body>
</html>

Web Framework/WebFramework/Views/Shared/_headerMenu.cshtml
<div>
    <div class="navbar-header">
        <div class="brand-container visible-xs">
            <a class="navbar-brand brand-name brand-name-xs" href="@Url.Action("Index", "Home", new { area = "" })">
                GuruIn.NET
            </a>
        </div>

        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#header-menu-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
    </div>

    <div>
        <div id="header-menu-collapse" class="collapse navbar-collapse text-uppercase">
            <ul id="menu" class="nav navbar-nav navbar-centre">
                <li class="hidden-xs">
                    <a class="brand-name brand-name-non-xs" href="@Url.Action("Index", "Home", new { area = "" })" role="button" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-home fa-1_2x"></i>
                        <span class="hidden-sm">GuruIn.NET</span>
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "Demos")" role="button" aria-haspopup="true" aria-expanded="false">
                        Learnings
                        <span class="arrow-down"></span>
                    </a>
                    <ul class="sub-menu-navbar dropdown-menu">
                        <li><a href="/Demos#bootstrap" onclick="return LoadContent('#bootstrap');">Bootstrap</a></li>
                        <li><a href="/Demos#jasmine" onclick="return LoadContent('#jasmine');">Jasmine Test</a></li>
                        <li><a href="/Demos#sass-less" onclick="return LoadContent('#sass-less');">Sass &amp; Scss</a></li>
                        <li><a href="/Demos#jshint" onclick="return LoadContent('#jshint');">JSHint</a></li>
                        <li><a href="/Demos#bower-npm" onclick="return LoadContent('#bower-npm');">npm &amp; Bower</a></li>
                        <li><a href="/Demos#git-gulp" onclick="return LoadContent('#git-gulp');">Git &amp; Gulp</a></li>
                        <li><a href="/Demos#angular" onclick="return LoadContent('#angular');">Angular JS</a></li>
                        <li><a href="/Demos#knockout" onclick="return LoadContent('#knockout');">Knockout JS</a></li>
                        <li><a href="/Demos#font-awesome" onclick="return LoadContent('#font-awesome');">Font Awesome</a></li>
                        <li><a href="/Demos#type-js" onclick="return LoadContent('#type-js');">Type Script</a></li>
                    </ul>
                </li>
                <li>
                    <a href="#" role="button" aria-haspopup="true" aria-expanded="false" onclick="return false;">
                        Framework
                        <span class="arrow-down"></span>
                    </a>
                    <ul class="sub-menu-navbar dropdown-menu">
                        <li>
                            <a href="@Url.Action("ComingUp", "Dashboard", new { area = "" })">
                                Global Asax
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Error Handling
                                <span class="arrow-right"></span>
                            </a>
                            <ul class="sub-menu-navbar dropdown-menu side-menu">
                                <li>
                                    <a href="#">
                                        Server Side
                                        <span class="arrow-right"></span>
                                    </a>
                                    <ul class="sub-menu-navbar dropdown-menu side-menu">
                                        <li>
                                            <a href="@Url.Action("Remove", "Dashboard", new { area = "" })">
                                                On Exception
                                            </a>
                                        </li>
                                        <li>
                                            <a href="@Url.Action("Remove", "BadController", new { area = "" })">
                                                Application Error
                                            </a>
                                        </li>
                                        <li>
                                            <a href="/a/b/c/d/e/f/g">
                                                Catch All
                                            </a>
                                        </li>
                                        <li>
                                            <a href="/asljefhp">
                                                Bad URL
                                            </a>
                                        </li>
                                    </ul>
                                </li>
                                <li>
                                    <a href="#" onclick="GenerateJsError();">
                                        Client Side
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <a href="@Url.Action("ComingUp", "Dashboard", new { area = "" })">
                                Security
                            </a>
                        </li>
                    </ul>
                </li>
                <li>
                    @Html.ActionLink("GDrive", "Index", "GDrive", new { area = "" }, null)
                </li>
                <li>
                    @Html.ActionLink("Fiddle", "Index", "Fiddle", new { area = "" }, null)
                </li>
                <li>
                    @Html.ActionLink("Blog", "AllPosts", "Home", new { area = "Blog" }, null)
                </li>
                <li>
                    @Html.ActionLink("eCommerce", "Index", "Ecommerce", new { area = "" }, null)
                </li>
                <li>
                    <a href="@Url.Action("List", "Dashboard", new { area = "" })">
                        Dashboard
                    </a>
                </li>
                <li style="display: none">
                    <a href="/Home" role="button" aria-haspopup="true" aria-expanded="false" onclick="return false;">
                        Myself
                        <span class="arrow-down"></span>
                    </a>
                    <ul class="sub-menu-navbar dropdown-menu">
                        <li>
                            @Html.ActionLink("About", "About", "Home", new { area = "" }, null)
                        </li>
                        <li>
                            @Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, null)
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</div>

Web Framework/WebFramework/Views/Shared/_jsErrorAlert.cshtml
<div id="js-error-alert-container"></div>

Web Framework/WebFramework/Views/Shared/_modalDialog.cshtml
@model WebFramework.ViewModels.ModalViewModel

<!-- Modal -->
<div class="modal-dialog" role="document">
    <div class="modal-content">

        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><i class="fa fa-times-circle"></i></button>
            <h4 class="modal-title" id="myModalLabel">@Model.Title</h4>
        </div>

        <div class="modal-body" style="max-height: 450px; overflow-y: auto">
            @Model.Body
        </div>

        <div class="modal-footer">
            <span class="btn btn-custom-default" data-dismiss="modal">
                @Model.Cancel &nbsp; <i class="fa fa-times"></i>
            </span>&nbsp; 
            <button class="btn btn-custom-success">
                @Model.Ok &nbsp; <i class="fa fa-check"></i>
            </button>
        </div>

    </div>
</div>

Web Framework/WebFramework/Views/Shared/_subMenu.cshtml
@model string

<div class="visible-sm visible-xs">
    <div style="display: table; margin: 0 auto">
        <button type="button" class="" data-toggle="collapse" data-target="#sub-menu-collapse" aria-expanded="false" aria-controls="sub-menu-collapse" style="padding: 0; margin: 0; border: 0">
            <span class="btn" style="color: #ddd; background-color: #333">
                <i class="fa fa-chevron-circle-down fa-1_1x"></i>
            </span>
        </button>
    </div>
    <div class="collapse" id="sub-menu-collapse" style="padding: 0">
        <!-- JS copies the sub menu contents (<ul>) from the below "sub-menu-items" -->
    </div>
</div>

<div class="visible-lg visible-md">
    <div id="sidebar-items">
        <ul class="list-group submenu">
            <li class="list-group-item">
                <a href="@Url.Action("List", "Dashboard")">
                    List Of Products
                </a>
                @if (!string.IsNullOrWhiteSpace(Model))
                {
                    <span class="badge">@Model</span>
                }
            </li>
            <li class="list-group-item">
                <a href="@Url.Action("Create", "Dashboard")">
                    Create New Product
                </a>
            </li>
            <li class="list-group-item">
                <a href="@Url.Action("Index", "Ecommerce")">
                    eCommerce
                </a>
                @if (!string.IsNullOrWhiteSpace(Model))
                {
                    <span class="badge">@Model</span>
                }
            </li>
        </ul>
    </div>
</div>

Web Framework/WebFramework/Views/Shared/_workInProgress.cshtml
<div id="work-in-progress">
    <span></span>
    <i class="fa fa-spinner fa-pulse fa-5x fa-fw "></i>
    <div></div>
</div>